// Generated blog posts data file.
// This file is managed by the admin panel. Manual edits may be overwritten.

const BLOG_POSTS = [
  {
    "slug": "chatgpt-may-be-coming-to-carplay",
    "title": "ChatGPT may be coming to Apple CarPlay",
    "publishedOn": "2026-02-06",
    "publishedLabel": "February 6, 2026",
    "hasArchive": true,
    "archivePath": "archive/chatgpt-may-be-coming-to-carplay.html",
    "indexHtml": "\n      <p>If you've spent any time with the current version of CarPlay, you know that Siri has long been the only voice assistant allowed in the driver's seat. However, a new report from <em>The Verge</em> suggests that Apple is finally getting ready to break that monopoly. According to the rumor, an upcoming iOS update could open the door for third-party AI chatbots—like ChatGPT, Google Gemini, and Claude—to integrate directly with the CarPlay interface. This would mark a significant shift in how Apple manages its automotive ecosystem, potentially allowing drivers to use more advanced conversational AI for hands-free tasks that Siri currently struggles to handle.</p>\n      <br />\n      <p>The move appears to be a response to the rapid evolution of generative AI and the fact that several automakers are already starting to bake their own AI voice assistants directly into vehicle dashboards. While you can technically use these chatbot apps on your iPhone today, they aren't optimized for the road; this update would reportedly introduce a \"voice-enabled\" category for CarPlay apps. This would allow users to trigger these assistants through the car's display and microphones, though the report notes that Apple doesn't plan to let you replace Siri entirely. You'd likely still need to open the specific app to use its voice mode, as the system-level \"Siri\" button and wake word will remain tied to Apple's own assistant.</p>\n      <br />\n      <p>While Apple is already working on its own major AI overhaul for Siri (including a high-profile partnership with Google), this rumored \"open-door\" policy suggests a more flexible approach to the dashboard. By allowing these third-party agents a spot on the screen, Apple seems to be prioritizing a safer, more native-feeling experience for users who are already turning to other LLMs for complex queries. There's no official word on whether this will arrive with a mid-cycle iOS 26 update or be saved for the debut of iOS 27, but it's a clear signal that the passenger-side experience is about to get a lot more talkative.</p>\n    ",
    "articleHtml": "\n      <p>If you've spent any time with the current version of CarPlay, you know that Siri has long been the only voice assistant allowed in the driver's seat. However, a new report from <em>The Verge</em> suggests that Apple is finally getting ready to break that monopoly. According to the rumor, an upcoming iOS update could open the door for third-party AI chatbots—like ChatGPT, Google Gemini, and Claude—to integrate directly with the CarPlay interface. This would mark a significant shift in how Apple manages its automotive ecosystem, potentially allowing drivers to use more advanced conversational AI for hands-free tasks that Siri currently struggles to handle.</p>\n      <br />\n      <p>The move appears to be a response to the rapid evolution of generative AI and the fact that several automakers are already starting to bake their own AI voice assistants directly into vehicle dashboards. While you can technically use these chatbot apps on your iPhone today, they aren't optimized for the road; this update would reportedly introduce a \"voice-enabled\" category for CarPlay apps. This would allow users to trigger these assistants through the car's display and microphones, though the report notes that Apple doesn't plan to let you replace Siri entirely. You'd likely still need to open the specific app to use its voice mode, as the system-level \"Siri\" button and wake word will remain tied to Apple's own assistant.</p>\n      <br />\n      <p>While Apple is already working on its own major AI overhaul for Siri (including a high-profile partnership with Google), this rumored \"open-door\" policy suggests a more flexible approach to the dashboard. By allowing these third-party agents a spot on the screen, Apple seems to be prioritizing a safer, more native-feeling experience for users who are already turning to other LLMs for complex queries. There's no official word on whether this will arrive with a mid-cycle iOS 26 update or be saved for the debut of iOS 27, but it's a clear signal that the passenger-side experience is about to get a lot more talkative.</p>\n    "
  },
  {
    "slug": "meta-blames-apple-for-failure",
    "title": "Meta blames Apple for failure",
    "publishedOn": "2026-02-05",
    "publishedLabel": "February 5, 2026",
    "hasArchive": true,
    "archivePath": "archive/meta-blames-apple-for-failure.html",
    "indexHtml": "\n      <p>It's no secret that there's no love lost between Meta and Apple, but the latest report from AppleInsider reveals that Mark Zuckerberg's frustrations with Cupertino are deeper and more personal than just a disagreement over privacy settings. Newly surfaced internal emails, which came to light through a lawsuit filed by the New Mexico Attorney General, show Zuckerberg complaining to his leadership team about what he perceives as a massive double standard. He argues that while Meta is constantly under the microscope for its impact on teen safety and mental health, Apple essentially gets a \"free pass\" for iMessage, which he claims facilitates similar behaviors without the same level of public or regulatory scrutiny.</p>\n      <br />\n      <p>The internal documents highlight a specific grievance: Zuckerberg feels that because iMessage is a private messaging service rather than a public-facing social feed, it escapes the \"intense scrutiny\" Meta faces regarding content moderation and child safety. In the emails, he expresses frustration that Meta is forced to spend billions on safety and human reviewers while Apple, in his view, doesn't have to account for how its tools are used by minors. He goes as far as to suggest that Apple isn't even looking for these problems, which allows them to maintain a cleaner reputation in the eyes of the public and lawmakers.</p>\n      <br />\n      <p>However, the article notes that Zuckerberg's comparison might be ignoring some fundamental differences in how these platforms operate. While Meta's business model is built on algorithmic engagement and public sharing, Apple's iMessage is an end-to-end encrypted communication tool. The report also points out that Apple actually has implemented several safety features, such as Communication Safety tools that blur sensitive content for minors, which contradicts Zuckerberg's internal claims that Apple does \"nothing.\" Ultimately, the piece paints a picture of a Meta CEO who feels unfairly targeted and is increasingly vocal—at least behind closed doors—about shifting the narrative toward his rivals.</p>\n    ",
    "articleHtml": "\n      <p>It's no secret that there's no love lost between Meta and Apple, but the latest report from AppleInsider reveals that Mark Zuckerberg's frustrations with Cupertino are deeper and more personal than just a disagreement over privacy settings. Newly surfaced internal emails, which came to light through a lawsuit filed by the New Mexico Attorney General, show Zuckerberg complaining to his leadership team about what he perceives as a massive double standard. He argues that while Meta is constantly under the microscope for its impact on teen safety and mental health, Apple essentially gets a \"free pass\" for iMessage, which he claims facilitates similar behaviors without the same level of public or regulatory scrutiny.</p>\n      <br />\n      <p>The internal documents highlight a specific grievance: Zuckerberg feels that because iMessage is a private messaging service rather than a public-facing social feed, it escapes the \"intense scrutiny\" Meta faces regarding content moderation and child safety. In the emails, he expresses frustration that Meta is forced to spend billions on safety and human reviewers while Apple, in his view, doesn't have to account for how its tools are used by minors. He goes as far as to suggest that Apple isn't even looking for these problems, which allows them to maintain a cleaner reputation in the eyes of the public and lawmakers.</p>\n      <br />\n      <p>However, the article notes that Zuckerberg's comparison might be ignoring some fundamental differences in how these platforms operate. While Meta's business model is built on algorithmic engagement and public sharing, Apple's iMessage is an end-to-end encrypted communication tool. The report also points out that Apple actually has implemented several safety features, such as Communication Safety tools that blur sensitive content for minors, which contradicts Zuckerberg's internal claims that Apple does \"nothing.\" Ultimately, the piece paints a picture of a Meta CEO who feels unfairly targeted and is increasingly vocal—at least behind closed doors—about shifting the narrative toward his rivals.</p>\n    "
  },
  {
    "slug": "apple-launches-creator-studio",
    "title": "Apple launches Creator Studio",
    "publishedOn": "2026-01-28",
    "publishedLabel": "January 28, 2026",
    "hasArchive": true,
    "archivePath": "archive/apple-launches-creator-studio.html",
    "indexHtml": "\n      <p>Apple launched Creator Studio today for iPad and Mac today for users who are looking to take advantage of all Apple's pro level apps all in one subscription. This new subscription is available for individuals (with up to 5 family members using Family Share) and Students.</p>\n      <br />\n      <p>The Individual Subscription is $12.99/month or $129/year or $2.99/month or $29/year for Students. \n      The suite includes the following pro apps.</p>\n      <ul class=\"list-disc list-inside ml-5\">\n        <li>Final Cut Pro</li>\n        <li>Motion</li>\n        <li>Compressor</li>\n        <li>Logic Pro</li>\n        <li>MainStage</li>\n        <li>Pixelmator Pro</li>\n      </ul>\n      <br />\n      <p>It also includes new templates and features for the following productivity apps</p>\n      <ul class=\"list-disc list-inside ml-5\">\n        <li>Numbers</li>\n        <li>Pages</li>\n        <li>Keynote</li>\n        <li>Freeform</li>\n      </ul>\n      <br />\n      <p>It is available now in the App Store, and Apple is offering a 30-day trial for those who are wishing to take advantage of it.</p>\n    ",
    "articleHtml": "\n      <p>Apple launched Creator Studio today for iPad and Mac today for users who are looking to take advantage of all Apple’s pro level apps all in one subscription. This new subscription is available for individuals (with up to 5 family members using Family Share) and Students.</p>\n      <br />\n      <p>The Individual Subscription is $12.99/month or $129/year or $2.99/month or $29/year for Students. \n      The suite includes the following pro apps.</p>\n      <ul class=\"list-disc list-inside ml-5\">\n        <li>Final Cut Pro</li>\n        <li>Motion</li>\n        <li>Compressor</li>\n        <li>Logic Pro</li>\n        <li>MainStage</li>\n        <li>Pixelmator Pro</li>\n      </ul>\n      <br />\n      <p>It also includes new templates and features for the following productivity apps</p>\n      <ul class=\"list-disc list-inside ml-5\">\n        <li>Numbers</li>\n        <li>Pages</li>\n        <li>Keynote</li>\n        <li>Freeform</li>\n      </ul>\n      <br />\n      <p>It is available now in the App Store, and Apple is offering a 30-day trial for those who are wishing to take advantage of it.</p>\n    "
  },
  {
    "slug": "tiktok-was-bought",
    "title": "TikTok was bought by a U.S. conglomerate of investors",
    "publishedOn": "2026-01-26",
    "publishedLabel": "January 26, 2026",
    "hasArchive": true,
    "archivePath": "archive/tiktok-was-bought.html",
    "indexHtml": "\n      <p>While it is not quite over, the saga of TikTok is soon going to come to an end, and I am not entirely sure how I feel about it. For those of you who haven't been paying attention. A law was passed last year to ban TikTok in the US because of foreign control from China and alleged concerns of National Security from Congress.</p> \n      <br />\n      <p><a href=\"https://www.buzzfeednews.com/article/jasonwells/trump-signs-tiktok-executive-order\">This fear is not new</a>, and has been around for a while now. But when Trump took office for a second term, he signed an executive order to bring TikTok back <a href=\"https://www.nbcnews.com/politics/supreme-court/tiktok-ban-supreme-court-ruling-bytedance-sell-rcna187150\">(after the Surpreme Court shot down a ban)</a> and vowed to find companies that would be willing to take on the burden of hosting TikTok in the US without giving China access to US data. While the intentions were sound, I suppose, I didn't think that it was honestly worth ripping apart a platform that millions of people used every day for allegations of National Security Threats, which the government still had not provided a foundation for... <a href=\"../blog/archive/tiktok-was-bought.html\">Read more</a></p> \n    ",
    "articleHtml": "\n      <p>While it is not quite over, the saga of TikTok is soon going to come to an end, and I am not entirely sure how I feel about it. For those of you who haven’t been paying attention. A law was passed last year to ban TikTok in the US because of foreign control from China and alleged concerns of National Security from Congress.</p> \n      <br />\n      <p><a href=\"https://www.buzzfeednews.com/article/jasonwells/trump-signs-tiktok-executive-order\">This fear is not new</a>, and has been around for a while now. But when Trump took office for a second term, he signed an executive order to bring TikTok back <a href=\"https://www.nbcnews.com/politics/supreme-court/tiktok-ban-supreme-court-ruling-bytedance-sell-rcna187150\">(after the Surpreme Court shot down a ban)</a> and vowed to find companies that would be willing to take on the burden of hosting TikTok in the US without giving China access to US data. While the intentions were sound, I suppose, I didn’t think that it was honestly worth ripping apart a platform that millions of people used every day for allegations of National Security Threats, which the government still had not provided a foundation for.</p> \n      <br />\n      <p>Like many others, I walked away from posting content on the platform out of concern for the platform being shut down until a deal had been made. Although the president had given us assurances that he would keep the platform open, many of us didn’t feel comfortable with the looming fact that this could all fall apart at any moment.</p>\n      <br />\n      <p><a href=\"https://www.engadget.com/social-media/we-have-more-details-on-the-tiktok-deal-including-some-ownership-statistics-163003507.html\">Nonetheless, according to Engadget</a>, the deal is supposed to finalize on January 22, 2026 pending final approval from the Chinese government. This deal would give Oracle, Silver Lake, and MGX stake in the company as well as maintaining some control from parent company ByteDance. In a statement to employees TikTok CEO Shou Chew said \"With these agreements in place, our focus must stay where it's always been — firmly on delivering for our users, creators, businesses and the global TikTok community,”</p>\n      <br />\n      <p>As always, we will share more information as it becomes available.</p>\n    "
  },
  {
    "slug": "we-messed-up",
    "title": "We messed up",
    "publishedOn": "2026-01-26",
    "publishedLabel": "January 26, 2026",
    "hasArchive": true,
    "archivePath": "archive/we-messed-up.html",
    "indexHtml": "\n      <p>Remember when we said we were going to move everything to Notion and host all of our content over there and that is was going to be easier to push out new content? Well that kind of backfired spectactularly. Put simply, we oversold and under-delivered on our commitment to make Notion our new platform and we decided to revert back to the GitHub project instead.</p>\n      <br />\n      <p>So here's the deal. We are putting the finishing touches on the new website, and we'll bring over the content over the course of this week. There wasn't a lot of content, so the transition should be pretty smooth. With that being said, we are revising our internal practices and will adjust accrdingly so that this mistakes like this don't happen again.</p>\n      <br />\n      <h1 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4\">What's new</h1>\n      <p>In this release we are bringing quality of life improvements to the overall experience, our main focus for this release is bringing video content directly to the website without having to leave the page. This change is actively being implemented and we are seeking feedback on the experience. It is important to note that we cannot control the experience that our partners bring with their video plugins, so please keep that in mind before submitting feedback.</p>\n    ",
    "articleHtml": "\n      <p>Remember when we said we were going to move everything to Notion and host all of our content over there and that is was going to be easier to push out new content? Well that kind of backfired spectactularly. Put simply, we oversold and under-delivered on our commitment to make Notion our new platform and we decided to revert back to the GitHub project instead.</p>\n      <br />\n      <p>So here's the deal. We are putting the finishing touches on the new website, and we'll bring over the content over the course of this week. There wasn't a lot of content, so the transition should be pretty smooth. With that being said, we are revising our internal practices and will adjust accrdingly so that this mistakes like this don't happen again.</p>\n      <br />\n      <h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4\">What's new</h2>\n      <p>In this release we are bringing quality of life improvements to the overall experience, our main focus for this release is bringing video content directly to the website without having to leave the page. This change is actively being implemented and we are seeking feedback on the experience. It is important to note that we cannot control the experience that our partners bring with their video plugins, so please keep that in mind before submitting feedback.</p>\n    "
  },
  {
    "slug": "sevan-core-platform-update-17-1",
    "title": "Introducing Sevan \"Plasma\" Core Update 17.1",
    "publishedOn": "2026-02-12",
    "publishedLabel": "February 12, 2026",
    "hasArchive": true,
    "archivePath": "archive/sevan-core-platform-update-17-1.html",
    "indexHtml": "<p>This release focuses on improving the overall experience on the front end and back end including administration and presentation. While most of the changes aren't front facing, they do impact the overall use of this website.</p>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's new</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Improvements to the blog experience. On the back end posts are now managed using a custom CMS platform specially developed for Sevan Core. We call it Plasma CMS. We'll talk more about it in the future.</li>\n<li>Dynamic sync between the blog and the homepage. The latest post now automatically populates without having to modify any code.</li>\n</ul>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's coming</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Account management – We are working on a system that will allow users to comment, share and manage their own account without leaving the website.</li>\n</ul>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's missing</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Plasma CMS is very basic right now. There aren't a lot of front-facing features that users can take advantage of and the management portal is very basic.</li>\n</ul>",
    "articleHtml": "<p>This release focuses on improving the overall experience on the front end and back end including administration and presentation. While most of the changes aren't front facing, they do impact the overall use of this website.</p>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's new</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Improvements to the blog experience. On the back end posts are now managed using a custom CMS platform specially developed for Sevan Core. We call it Plasma CMS. We'll talk more about it in the future.</li>\n<li>Dynamic sync between the blog and the homepage. The latest post now automatically populates without having to modify any code.</li>\n</ul>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's coming</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Account management – We are working on a system that will allow users to comment, share and manage their own account without leaving the website.</li>\n</ul>\n<h2 class=\"text-2xl md:text-3xl font-semibold tracking-tight mb-4 mt-6\">What's missing</h2>\n<ul class=\"list-disc list-inside ml-5 space-y-1\">\n<li>Plasma CMS is very basic right now. There aren't a lot of front-facing features that users can take advantage of and the management portal is very basic.</li>\n</ul>"
  }
];

if (typeof window !== 'undefined') {
  window.BLOG_POSTS = BLOG_POSTS;
}

if (typeof module !== 'undefined') {
  module.exports = BLOG_POSTS;
}
